version: '3.3'

services:
  wp_dev:
    depends_on:
      - wp_dev_db
    image: wordpress:latest
    volumes:
    - type: bind
      source: ./wp-content
      target: /var/www/html/wp-content
    ports:
      - "4000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_dev_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  wp_dev_db:
    image: mysql:5.7
    volumes:
      - wp_db_data:/var/lib/mysql
      - ./database/fresh_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wp_dev_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_dev_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 4001:80
    volumes:
      - /sessions
    links:
      - wp_dev_db:db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password

volumes:
    wp_dev_files:
    wp_db_data: